version: '3.5'
services:
  php-fpm:
    build: ./docker/php
    image: jefffrade/api:php-fpm
    restart: on-failure
    container_name: jefffrade-api-php-fpm
    command: php-fpm
    links:
      - mysql
      - mongodb
    volumes:
      - ./:/projeto
    networks:
      - app
      - db
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 9000 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    build: ./docker/nginx
    image: jefffrade/api:nginx
    restart: on-failure
    container_name: jefffrade-api-nginx
    command: nginx -g "daemon off;"
    links:
      - php-fpm
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/projeto
    networks:
      - app
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 80 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  mysql:
    build: ./docker/mysql
    image: jefffrade/api:mysql
    restart: on-failure
    container_name: jefffrade-api-mysql
    volumes:
      - "${DOCKER_DATA_PATH}/mysql:/var/lib/mysql"
    command:
      - "--innodb_use_native_aio=0"
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - db
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 3306 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  mongodb:
    build: ./docker/mongodb
    image: jefffrade/api:mongodb
    restart: on-failure
    container_name: jefffrade-api-mongodb
    volumes:
      - ${DOCKER_DATA_PATH}/mongo:/data/db
      - ./docker/mongodb/backup:/backup
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
    networks:
      - db
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 27017 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

networks:
  app:
  db:
